// Talent Register
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
// Talent Login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
// Talent User Auth
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
//
export const CLEAR_SERVER_ERRORS = "CLEAR_SERVER_ERRORS";
export const LOGOUT_USER = "LOGOUT_USER";
export const AUTH_LOADING_TRUE = "AUTH_LOADING_TRUE";
export const AUTH_LOADING_FALSE = "AUTH_LOADING_FALSE";

export const SAVE_TALENT_PROFILE_SUCCESS = "SAVE_TALENT_PROFILE_SUCCESS";
export const SAVE_TALENT_PROFILE_FAILURE = "SAVE_TALENT_PROFILE_FAILURE";
export const RESET_TALENT_PROFILE_BOOLEAN = "RESET_TALENT_PROFILE_BOOLEAN";
export const RESET_NOTIFICATION_SETTING = "RESET_NOTIFICATION_SETTING";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILURE = "UPDATE_PASSWORD_FAILURE";
export const APP_CONFIGS_LOADED = "APP_CONFIGS_LOADED";
export const APP_CONFIGS_ERROR = "APP_CONFIGS_ERROR";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAILURE = "UPDATE_FAILURE";
export const UPDATE_EVALUATION_SUCCESS = "UPDATE_EVALUATION_SUCCESS";
export const UPDATE_EVALUATION_FAILURE = "UPDATE_EVALUATION_FAILURE";
export const TM_LOADED = "TM_LOADED";
export const TM_ERROR = "TM_ERROR";

// Talent Calendar
export const TALENT_CALENDAR_LOADED = "TALENT_CALENDAR_LOADED";
export const TALENT_CALENDAR_API_RESPONSE = "TALENT_CALENDAR_API_RESPONSE";
export const UPDATE_CALENDER_TYPE = "UPDATE_CALENDER_TYPE";

// Sidebar
export const UPDATE_SIDEBAR_SUCCESS = "UPDATE_SIDEBAR_SUCCESS";
export const UPDATE_SIDEBAR_FAILURE = "UPDATE_SIDEBAR_FAILURE";

// company

export const COMPANY_REQUESTS_LOADED = "COMPANY_REQUESTS_LOADED";
export const COMPANY_REQUEST_LOADED = "COMPANY_REQUEST_LOADED";
export const COMPANY_REQUESTS_LOADED_ERROR = "COMPANY_REQUESTS_LOADED_ERROR";
export const SERVER_ERROR = "SERVER_ERROR";
export const SET_COMPANY_NAV_ITEM = "SET_COMPANY_NAV_ITEM";
export const COMPANIES_LOADED = "COMPANIES_LOADED";
export const COMPANY_FOR_ASSIGN = "COMPANY_FOR_ASSIGN";
export const UPDATE_MAIL_TOKEN = "UPDATE_MAIL_TOKEN";
export const ALL_INVITES_LOADED = "ALL_INVITES_LOADED";
export const INVITE_POSITION_DETAILS_LOADED = "INVITE_POSITION_DETAILS_LOADED";
export const INVITE_OFFER_DETAILS_LOADED = "INVITE_OFFER_DETAILS_LOADED";
export const ALL_INVITES_POSITION_DETAILS_LOADED =
  "ALL_INVITES_POSITION_DETAILS_LOADED";
export const RECRUITMENT_DETAILS_LOADED = "RECRUITMENT_DETAILS_LOADED";
export const INTERVIEW_DETAILS_LOADED = "INTERVIEW_DETAILS_LOADED";
export const CURRENT_NAVBAR_BUTTON = "CURRENT_NAVBAR_BUTTON";
export const TALENT_TIMEZONE = "TALENT_TIMEZONE";
