// Talent Register
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
// Talent Login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
// Talent User Auth
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
//
export const CLEAR_SERVER_ERRORS = "CLEAR_SERVER_ERRORS";
export const LOGOUT_USER = "LOGOUT_USER";
export const AUTH_LOADING_TRUE = "AUTH_LOADING_TRUE";
export const SET_SIDEBAR_KEY = "SET_SIDEBAR_KEY";

export const SAVE_TALENT_PROFILE_SUCCESS = "SAVE_TALENT_PROFILE_SUCCESS";
export const SAVE_TALENT_PROFILE_FAILURE = "SAVE_TALENT_PROFILE_FAILURE";
export const RESET_TALENT_PROFILE_BOOLEAN = "RESET_TALENT_PROFILE_BOOLEAN";
export const RESET_NOTIFICATION_SETTING = "RESET_NOTIFICATION_SETTING";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILURE = "UPDATE_PASSWORD_FAILURE";
export const APP_CONFIGS_LOADED = "APP_CONFIGS_LOADED";
export const APP_CONFIGS_ERROR = "APP_CONFIGS_ERROR";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAILURE = "UPDATE_FAILURE";
export const UPDATE_EVALUATION_SUCCESS = "UPDATE_EVALUATION_SUCCESS";
export const UPDATE_EVALUATION_FAILURE = "UPDATE_EVALUATION_FAILURE";
export const TM_LOADED = "TM_LOADED";
export const TM_ERROR = "TM_ERROR";

export const FILTER_APP_CONFIGS = "FILTER_APP_CONFIGS";
export const SET_APP_CONFIG_KEYS = "SET_APP_CONFIG_KEYS";
export const COEFFICIENT_CONFIGS = "COEFFICIENT_CONFIGS";

// Talent Calendar
export const TALENT_CALENDAR_LOADED = "TALENT_CALENDAR_LOADED";
export const TALENT_CALENDAR_API_RESPONSE = "TALENT_CALENDAR_API_RESPONSE";
export const UPDATE_CALENDER_TYPE = "UPDATE_CALENDER_TYPE";

// Talent

export const TALENTS_LOADED = "TALENTS_LOADED";
export const TALENT_LOADED = "TALENT_LOADED";
export const TALENTS_LOADED_ERROR = "TALENTS_LOADED_ERROR";
export const ALL_TALENTS_LOADED_COUNT = "ALL_TALENTS_LOADED_COUNT";
export const TALENT_EVALUATION_LOADED = "TALENT_EVALUATION_LOADED";
export const TALENT_EVALUATION_LOADED_ERROR = "TALENT_EVALUATION_LOADED_ERROR";
export const TALENT_MANAGER_MEETING_LOADED = "TALENT_MANAGER_MEETING_LOADED";
export const TALENTS_MANAGER_MEETING_LOADED_ERROR =
  "TALENTS_MANAGER_MEETING_LOADED_ERROR";
export const TALENT_PROF_INTERVIEW_LOADED = "TALENT_PROF_INTERVIEW_LOADED";
export const TALENT_PROF_INTERVIEW_LOADED_ERROR =
  "TALENT_PROF_INTERVIEW_LOADED_ERROR";
export const ALL_TALENTS_COUNT_LOADED = "ALL_TALENTS_COUNT_LOADED";
export const ALL_TALENTS_COUNT_LOADED_ERROR = "ALL_TALENTS_COUNT_LOADED_ERROR";

export const BTN_LOADING_TRUE = "BTN_LOADING_TRUE";

// company

export const SELECTED_POSITION_NULL = "SELECTED_POSITION_NULL";
export const COMPANY_REQUESTS_LOADED = "COMPANY_REQUESTS_LOADED";
export const COMPANY_REQUEST_LOADED = "COMPANY_REQUEST_LOADED";
export const COMPANY_REQUESTS_LOADED_ERROR = "COMPANY_REQUESTS_LOADED_ERROR";
export const SERVER_ERROR = "SERVER_ERROR";
export const SET_COMPANY_NAV_ITEM = "SET_COMPANY_NAV_ITEM";
export const COMPANIES_LOADED = "COMPANIES_LOADED";
export const COMPANY_FOR_ASSIGN = "COMPANY_FOR_ASSIGN";
export const UPDATE_MAIL_TOKEN = "UPDATE_MAIL_TOKEN";
export const REMOVE_MAIL_TOKEN = "REMOVE_MAIL_TOKEN";
export const COMPANY_LOADED = "COMPANY_LOADED";
export const COMPANY_USERS_LOADED = "COMPANY_USERS_LOADED";
export const COMPANY_POSITIONS_LOADED = "COMPANY_POSITIONS_LOADED";
export const INVITE_USER_SUCCESS = "INVITE_USER_SUCCESS";
export const COMPANY_AND_REQUESTS_COUNT_LOADED =
  "COMPANY_AND_REQUESTS_COUNT_LOADED";
export const SET_COMPANY_TAB_PANEL_KEY = "SET_COMPANY_TAB_PANEL_KEY";
export const COMPANY_SUGGESTIONS = "COMPANY_SUGGESTIONS";

// Talent managers

export const TALENT_MANAGERS_LOADED = "TALENT_MANAGERS_LOADED";
export const ACCOUNT_MANAGERS_LOADED = "ACCOUNT_MANAGERS_LOADED";
export const ALL_ACCOUNT_MANAGERS = "ALL_ACCOUNT_MANAGERS";
export const ACCOUNT_MANAGER = "ACCOUNT_MANAGER";

// Positions
export const POSITIONS_API_ERROR = "POSITIONS_API_ERROR";
export const ALL_COMPANIES_POSITIONS_LOADED = "ALL_COMPANIES_POSITIONS_LOADED";
export const SET_POSITION_NAV_ITEM = "SET_POSITION_NAV_ITEM";
export const SET_POSITION_SIDEBAR_KEY = "SET_POSITION_SIDEBAR_KEY";
export const POSITIONS_DETAILS_LOADED = "POSITIONS_DETAILS_LOADED";
export const POSITIONS_BTN_LOADING_TRUE = "POSITIONS_BTN_LOADING_TRUE";
export const FILTERED_POSITION_TALENTS_LOADED =
  "FILTERED_POSITION_TALENTS_LOADED";
export const RECRUITMENT_CANDIDATES_LIST_LOADED =
  "RECRUITMENT_CANDIDATES_LIST_LOADED";
export const FILTERED_POSITION_TALENTS_NULL = "FILTERED_POSITION_TALENTS_NULL";
export const UPDATE_POSITION_SUCCESS = "UPDATE_POSITION_SUCCESS";
export const UPDATE_POSITION_FAILURE = "UPDATE_POSITION_FAILURE";
export const NULL_ALL_POSITION_RESOURCES = "NULL_ALL_POSITION_RESOURCES";
export const CURRENT_GROUP_INDEX = "CURRENT_GROUP_INDEX";
export const POSITIONS_COUNT = "POSITIONS_COUNT";
export const SELECTED_TALENT_POSITIONS_LOADED =
  "SELECTED_TALENT_POSITIONS_LOADED";
export const SELECTED_POSITION_TALENT_NULL = "SELECTED_POSITION_TALENT_NULL";
export const CURRENT_STAFF_NAVBAR_BUTTON = "CURRENT_STAFF_NAVBAR_BUTTON";
export const PROCESSED_POSITION_TALENTS_LOADED =
  "PROCESSED_POSITION_TALENTS_LOADED";
export const PROCESSED_POSITION_TALENTS_REMOVE =
  "PROCESSED_POSITION_TALENTS_REMOVE";
