// Talent Register
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
// Talent Login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
// Talent User Auth
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
//
export const CLEAR_USER_ERRORS = "CLEAR_USER_ERRORS";
export const CLEAR_SERVER_ERRORS = "CLEAR_SERVER_ERRORS";
export const LOGOUT_USER = "LOGOUT_USER";
export const AUTH_LOADING_TRUE = "AUTH_LOADING_TRUE";

export const SAVE_TALENT_PROFILE_SUCCESS = "SAVE_TALENT_PROFILE_SUCCESS";
export const SAVE_TALENT_PROFILE_FAILURE = "SAVE_TALENT_PROFILE_FAILURE";
export const RESET_TALENT_PROFILE_BOOLEAN = "RESET_TALENT_PROFILE_BOOLEAN";
export const RESET_NOTIFICATION_SETTING = "RESET_NOTIFICATION_SETTING";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILURE = "UPDATE_PASSWORD_FAILURE";
export const APP_CONFIGS_LOADED = "APP_CONFIGS_LOADED";
export const APP_CONFIGS_ERROR = "APP_CONFIGS_ERROR";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAILURE = "UPDATE_FAILURE";
export const UPDATE_EVALUATION_SUCCESS = "UPDATE_EVALUATION_SUCCESS";
export const UPDATE_EVALUATION_FAILURE = "UPDATE_EVALUATION_FAILURE";
export const TM_LOADED = "TM_LOADED";
export const TM_ERROR = "TM_ERROR";

// Talent Calendar
export const TALENT_CALENDAR_LOADED = "TALENT_CALENDAR_LOADED";
export const TALENT_CALENDAR_API_RESPONSE = "TALENT_CALENDAR_API_RESPONSE";
export const UPDATE_CALENDER_TYPE = "UPDATE_CALENDER_TYPE";

// Talent

export const TALENTS_LOADED = "TALENTS_LOADED";
export const TALENT_LOADED = "TALENT_LOADED";
export const TALENTS_LOADED_ERROR = "TALENTS_LOADED_ERROR";
export const ALL_TALENTS_LOADED_COUNT = "ALL_TALENTS_LOADED_COUNT";
export const TALENT_EVALUATION_LOADED = "TALENT_EVALUATION_LOADED";
export const TALENT_EVALUATION_LOADED_ERROR = "TALENT_EVALUATION_LOADED_ERROR";
export const TALENT_MANAGER_MEETING_LOADED = "TALENT_MANAGER_MEETING_LOADED";
export const TALENTS_MANAGER_MEETING_LOADED_ERROR =
  "TALENTS_MANAGER_MEETING_LOADED_ERROR";
export const TALENT_PROF_INTERVIEW_LOADED = "TALENT_PROF_INTERVIEW_LOADED";
export const TALENT_PROF_INTERVIEW_LOADED_ERROR =
  "TALENT_PROF_INTERVIEW_LOADED_ERROR";
export const ALL_TALENTS_COUNT_LOADED = "ALL_TALENTS_COUNT_LOADED";
export const ALL_TALENTS_COUNT_LOADED_ERROR = "ALL_TALENTS_COUNT_LOADED_ERROR";
export const BTN_LOADING_TRUE_TALENT = "BTN_LOADING_TRUE_TALENT";

export const BTN_LOADING_TRUE = "BTN_LOADING_TRUE";
export const COMPANY_REQUEST_LOADED = "COMPANY_REQUEST_LOADED";
export const SERVER_ERROR = "SERVER_ERROR";
export const UPDATE_MAIL_TOKEN = "UPDATE_MAIL_TOKEN";
export const COMPANY_USERS_LOADED = "COMPANY_USERS_LOADED";
export const COMPANY_LOADED = "COMPANY_LOADED";
export const INVITE_USER_SUCCESS = "INVITE_USER_SUCCESS";

// Company
export const COMPANY_POSITION_DETAILS_LOADED =
  "COMPANY_POSITION_DETAILS_LOADED";
export const COMPANY_POSITIONS_LOADED = "COMPANY_POSITIONS_LOADED";
export const BTN_LOADING_TRUE_POSITIONS = "BTN_LOADING_TRUE_POSITIONS";
export const LATEST_COMPANY_POSITION_CREATED =
  "LATEST_COMPANY_POSITION_CREATED";
export const LATEST_COMPANY_POSITION_NULL = "LATEST_COMPANY_POSITION_NULL";
export const RECRUITMENT_CANDIDATES_LIST_LOADED =
  "RECRUITMENT_CANDIDATES_LIST_LOADED";
export const COMPANY_TIMEZONE = "COMPANY_TIMEZONE";

// position

export const SET_SELECTED_POSITION_ID = "SET_SELECTED_POSITION_ID";
export const SET_SELECTED_POSITION_RECRUITMENT =
  "SET_SELECTED_POSITION_RECRUITMENT";
export const COMPANY_OFFER_LOADED = "COMPANY_OFFER_LOADED";
export const UPDATE_FAILURE_POSITION = "UPDATE_FAILURE_POSITION";
export const UPDATE_SUCCESS_POSITION = "UPDATE_SUCCESS_POSITION";
export const RESET_NOTIFICATION_SETTING_POSITION =
  "RESET_NOTIFICATION_SETTING_POSITION";
export const CLEAR_SERVER_ERRORS_POSITION = "CLEAR_SERVER_ERRORS_POSITION";
export const COMPANY_INTERVIEW_LOADED = "COMPANY_INTERVIEW_LOADED";
export const COMPANY_CALENDAR_LOADED = "COMPANY_CALENDAR_LOADED";
export const BTN_LOADING_FALSE = "BTN_LOADING_FALSE";
export const COMPANY_POSITION_DETAILS_NULL = "COMPANY_POSITION_DETAILS_NULL";
export const TALENT_OFFERS_LOADED = "TALENT_OFFERS_LOADED";
export const COMPANY_NOTIFICATIONS_LOADED = "COMPANY_NOTIFICATIONS_LOADED";
export const POSITION_NOTIFICATIONS_LOADED = "POSITION_NOTIFICATIONS_LOADED";
export const CURRENT_SETTINGS_NAVBAR_BUTTON = "CURRENT_SETTINGS_NAVBAR_BUTTON";
export const CURRENT_HIRE_NAVBAR_BUTTON = "CURRENT_HIRE_NAVBAR_BUTTON";
export const COMPANY_ACTIVE_POSITIONS_LOADED =
  "COMPANY_ACTIVE_POSITIONS_LOADED";
export const COMPANY_ALL_POSITIONS_TYPE = "COMPANY_ALL_POSITIONS_TYPE";
export const NEW_POSITION_SKILLS = "NEW_POSITION_SKILLS";
export const NEW_POSITION_FEATURES = "NEW_POSITION_FEATURES";
export const NEW_POSITION_ROLE_FEATURES = "NEW_POSITION_ROLE_FEATURES";
export const NEW_POSITION_HIRING_TEAM = "NEW_POSITION_HIRING_TEAM";
export const NEW_POSITION_MANAGEMENT_EXP = "NEW_POSITION_MANAGEMENT_EXP";
